version: '2'
services:
  photon:
    build:
      context: .
      dockerfile: Dockerfile
    image: s3pweb/photon-geocoder:latest
    #network_mode: host
    command: import fr latest
    volumes:
      - ./data:/photon/photon_data
    #ports:
    #  - 2322:2322

volumes:
  data:
    driver: local
